go: 1.6.2
repository:
    path: github.com/prometheus/statsd_exporter
build:
    flags: -a -tags 'netgo static_build'
    ldflags: |
        -X main.Version={{.Version}}

tarball:
    files:
        - LICENSE
        - NOTICE
